package org.point85.app;

public enum Images {
	POINT85, NEW, ADD, REMOVE, SAVE, SAVE_ALL, DELETE, REFRESH, REFRESH_ALL, OK, CANCEL, UPDATE, CHOOSE, 
	UOM, CONVERT, SOURCE, IMPORT, REASON, MATERIAL, SCHEDULE, SCRIPT, CONNECT, DISCONNECT, CLEAR, TAG, 
	EXECUTE, APPLY, START, STOP, DASHBOARD, FOLDER, VALUE, CHANGED, CATEGORY, COLLECTOR, ENTERPRISE, SITE, 
	AREA, LINE, CELL, EQUIPMENT, OPC_UA, OPC_DA, HTTP, RMQ, JMS, MQTT, MODBUS, DB, FILE, WEB, STARTUP, SHUTDOWN, 
	WATCH, SPLASH, ABOUT, CHOOSE_FILE, SHIFT, PRODUCT, SETUP, AVAILABILITY, CHARTXY, READ, WRITE, HELP, CRON, KAFKA, EMAIL, 
	PROFICY, FILTER, SOURCE_MENU, EDITOR_MENU, TOOL_MENU, HELP_MENU, BACKUP, RESTORE;
}
