package org.point85.app;

public enum ImageEnum {
	POINT85, NEW, ADD, REMOVE, SAVE, SAVE_ALL, DELETE, REFRESH, REFRESH_ALL, OK, CANCEL, UPDATE, CHOOSE, UOM, CONVERT, 
	SOURCE, IMPORT, REASON, MATERIAL, SCHEDULE, SCRIPT, CONNECT, DISCONNECT, CLEAR, TAG, EXECUTE, APPLY, START, STOP, DASHBOARD, 
	FOLDER, VALUE, CHANGED, CATEGORY, COLLECTOR,
	ENTERPRISE, SITE, AREA, LINE, CELL, EQUIPMENT,
	OPC_UA, OPC_DA, HTTP, RMQ, WEB;
}
