-- Oracle script file, schema version 5
-- set to your schema and tablespace names

--------------------------------------------------------
--  DDL for Table PLANT_ENTITY
--------------------------------------------------------
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE "SYSTEM"."PLANT_ENTITY"';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/
CREATE TABLE "SYSTEM"."PLANT_ENTITY" 
(	
  "ENT_KEY" NUMBER(19,0) GENERATED ALWAYS AS IDENTITY, 
	"VERSION" NUMBER(10,0) NULL, 
	"NAME" NVARCHAR2(64) NULL, 
	"DESCRIPTION" NVARCHAR2(256) NULL, 
	"PARENT_KEY" NUMBER(19,0) NULL, 
	"HIER_LEVEL" NVARCHAR2(16) NULL, 
	"RETENTION" NUMBER(19,0) NULL,
	PRIMARY KEY (ENT_KEY)
) TABLESPACE "SYSTEM" ;
/
CREATE UNIQUE INDEX "SYSTEM"."IDX_ENT_NAME" ON "SYSTEM"."PLANT_ENTITY" ("NAME") TABLESPACE "SYSTEM" ;
/
--------------------------------------------------------
--  DDL for Table REASON
--------------------------------------------------------
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE "SYSTEM"."REASON"';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/
CREATE TABLE "SYSTEM"."REASON" 
   (	
    "REASON_KEY" NUMBER(19,0) GENERATED ALWAYS AS IDENTITY, 
	"VERSION" NUMBER(10,0) NULL, 
	"NAME" NVARCHAR2(64) NULL, 
	"DESCRIPTION" NVARCHAR2(128) NULL, 
	"PARENT_KEY" NUMBER(19,0) NULL, 
	"LOSS" NVARCHAR2(32) NULL,
	PRIMARY KEY (REASON_KEY)
   ) TABLESPACE "SYSTEM" ;
/   
CREATE UNIQUE INDEX "SYSTEM"."IDX_REASON_NAME" ON "SYSTEM"."REASON" ("NAME") TABLESPACE "SYSTEM" ;
/   
--------------------------------------------------------
--  DDL for Table MATERIAL
--------------------------------------------------------
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE "SYSTEM"."MATERIAL"';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/
CREATE TABLE "SYSTEM"."MATERIAL" 
   (	
    "MAT_KEY" NUMBER(19,0) GENERATED ALWAYS AS IDENTITY, 
	"VERSION" NUMBER(10,0) NULL, 
	"NAME" NVARCHAR2(64) NULL, 
	"DESCRIPTION" NVARCHAR2(128) NULL, 
	"CATEGORY" NVARCHAR2(32) NULL,
	PRIMARY KEY (MAT_KEY)
   ) TABLESPACE "SYSTEM" ;
/
CREATE UNIQUE INDEX "SYSTEM"."IDX_MATERIAL_NAME" ON "SYSTEM"."MATERIAL" ("NAME") TABLESPACE "SYSTEM" ;
/
--------------------------------------------------------
--  DDL for Table EQUIPMENT_MATERIAL
--------------------------------------------------------
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE "SYSTEM"."EQUIPMENT_MATERIAL"';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/
CREATE TABLE "SYSTEM"."EQUIPMENT_MATERIAL" 
   (	
    "EM_KEY" NUMBER(19,0) GENERATED ALWAYS AS IDENTITY,  
	"EQ_KEY" NUMBER(19,0) NULL, 
	"MAT_KEY" NUMBER(19,0) NULL, 
	"OEE_TARGET" BINARY_DOUBLE NULL, 
	"RUN_AMOUNT" BINARY_DOUBLE NULL, 
	"RUN_UOM_KEY" NUMBER(19,0) NULL, 
	"REJECT_UOM_KEY" NUMBER(19,0) NULL, 
	"IS_DEFAULT" NUMBER(5,0) NOT NULL,
	PRIMARY KEY (EM_KEY)
   ) TABLESPACE "SYSTEM" ;
/   
--------------------------------------------------------
--  DDL for Table DATA_SOURCE
--------------------------------------------------------
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE "SYSTEM"."DATA_SOURCE"';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/
CREATE TABLE "SYSTEM"."DATA_SOURCE" 
   (	
    "SOURCE_KEY" NUMBER(19,0) GENERATED ALWAYS AS IDENTITY, 
	"VERSION" NUMBER(10,0) NOT NULL, 
	"NAME" NVARCHAR2(64) NOT NULL, 
	"DESCRIPTION" NVARCHAR2(128) NULL, 
	"TYPE" NVARCHAR2(16) NOT NULL, 
	"HOST" NVARCHAR2(128) NULL, 
	"USER_NAME" NVARCHAR2(64) NULL, 
	"PASSWORD" NVARCHAR2(64) NULL, 
	"PORT" NUMBER(10,0) NULL, 
	"END_PATH" NVARCHAR2(128) NULL,
	"SEC_POLICY" NVARCHAR2(64) NULL,
	"MSG_MODE" NVARCHAR2(64) NULL,
	"KEYSTORE" NVARCHAR2(128) NULL,
	"KEYSTORE_PWD" NVARCHAR2(64) NULL,
	PRIMARY KEY (SOURCE_KEY)
   ) TABLESPACE "SYSTEM" ;
/
CREATE UNIQUE INDEX "SYSTEM"."IDX_SOURCE_NAME" ON "SYSTEM"."DATA_SOURCE" ("NAME") TABLESPACE "SYSTEM" ;
/
--------------------------------------------------------
--  DDL for Table EVENT_RESOLVER
--------------------------------------------------------
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE "SYSTEM"."EVENT_RESOLVER"';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/
CREATE TABLE "SYSTEM"."EVENT_RESOLVER" 
   (	
    "ER_KEY" NUMBER(19,0) GENERATED ALWAYS AS IDENTITY,  
	"ENT_KEY" NUMBER(19,0) NULL, 
	"SOURCE_ID" NVARCHAR2(128) NULL, 
	"SCRIPT" NVARCHAR2(2000) NULL, 
	"SOURCE_KEY" NUMBER(19,0) NULL, 
	"PERIOD" NUMBER(10,0) NULL, 
	"ER_TYPE" NVARCHAR2(16) NULL, 
	"DATA_TYPE" NVARCHAR2(32) NULL, 
	"COLLECT_KEY" NUMBER(19,0) NULL,
	PRIMARY KEY (ER_KEY)
   ) TABLESPACE "SYSTEM" ;
/
CREATE UNIQUE INDEX "SYSTEM"."IDX_SOURCE_ID" ON "SYSTEM"."EVENT_RESOLVER" ("SOURCE_ID") TABLESPACE "SYSTEM" ;
/
--------------------------------------------------------
--  DDL for Table UOM
--------------------------------------------------------
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE "SYSTEM"."UOM"';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/
CREATE TABLE "SYSTEM"."UOM" 
   (	
    "UOM_KEY" NUMBER(19,0) GENERATED ALWAYS AS IDENTITY,   
	"VERSION" NUMBER(10,0) NOT NULL, 
	"NAME" NVARCHAR2(64) NULL, 
	"SYMBOL" NVARCHAR2(16) NOT NULL, 
	"DESCRIPTION" NVARCHAR2(512) NULL, 
	"CATEGORY" NVARCHAR2(64) NULL, 
	"UNIT_TYPE" NVARCHAR2(32) NULL, 
	"UNIT" NVARCHAR2(32) NULL, 
	"CONV_FACTOR" BINARY_DOUBLE NULL, 
	"CONV_UOM_KEY" NUMBER(19,0) NULL, 
	"CONV_OFFSET" BINARY_DOUBLE NULL, 
	"BRIDGE_FACTOR" BINARY_DOUBLE NULL, 
	"BRIDGE_UOM_KEY" NUMBER(19,0) NULL, 
	"BRIDGE_OFFSET" BINARY_DOUBLE NULL, 
	"UOM1_KEY" NUMBER(19,0) NULL, 
	"EXP1" NUMBER(10,0) NULL, 
	"UOM2_KEY" NUMBER(19,0) NULL, 
	"EXP2" NUMBER(10,0) NULL,
	PRIMARY KEY (UOM_KEY)
   ) TABLESPACE "SYSTEM" ;
/
CREATE UNIQUE INDEX "SYSTEM"."IDX_SYMBOL" ON "SYSTEM"."UOM" ("SYMBOL") TABLESPACE "SYSTEM" ;
/   
--------------------------------------------------------
--  DDL for Table WORK_SCHEDULE
--------------------------------------------------------
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE "SYSTEM"."WORK_SCHEDULE"';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/
CREATE TABLE "SYSTEM"."WORK_SCHEDULE" 
   (	
    "WS_KEY" NUMBER(19,0) GENERATED ALWAYS AS IDENTITY,   
	"VERSION" NUMBER(10,0) NULL, 
	"NAME" NVARCHAR2(64) NULL, 
	"DESCRIPTION" NVARCHAR2(512)NULL,
	PRIMARY KEY (WS_KEY)
   ) TABLESPACE "SYSTEM" ;
/
CREATE UNIQUE INDEX "SYSTEM"."IDX_SCHED_NAME" ON "SYSTEM"."WORK_SCHEDULE" ("NAME") TABLESPACE "SYSTEM" ;
/  
--------------------------------------------------------
--  DDL for Table SHIFT
--------------------------------------------------------
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE "SYSTEM"."SHIFT"';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/
CREATE TABLE "SYSTEM"."SHIFT" 
   (	
    "SHIFT_KEY" NUMBER(19,0) GENERATED ALWAYS AS IDENTITY,  
	"NAME" NVARCHAR2(64) NULL, 
	"DESCRIPTION" NVARCHAR2(128) NULL, 
	"START_TIME" TIMESTAMP(3) NULL, 
	"DURATION" NUMBER(19,0) NULL, 
	"WS_KEY" NUMBER(19,0) NULL,
	PRIMARY KEY (SHIFT_KEY)
   ) TABLESPACE "SYSTEM" ;
/
CREATE UNIQUE INDEX "SYSTEM"."IDX_SHIFT.NAME_WS" ON "SYSTEM"."SHIFT" ("NAME", "WS_KEY") TABLESPACE "SYSTEM" ;
/  
--------------------------------------------------------
--  DDL for Table TEAM
--------------------------------------------------------
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE "SYSTEM"."TEAM"';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/
CREATE TABLE "SYSTEM"."TEAM" 
   (	
    "TEAM_KEY" NUMBER(19,0) GENERATED ALWAYS AS IDENTITY, 
	"NAME" NVARCHAR2(64) NULL, 
	"DESCRIPTION" NVARCHAR2(128) NULL, 
	"WS_KEY" NUMBER(19,0) NULL, 
	"ROTATION_KEY" NUMBER(19,0) NULL, 
	"ROTATION_START" DATE NULL,
	PRIMARY KEY (TEAM_KEY)
   ) TABLESPACE "SYSTEM" ;
/
CREATE UNIQUE INDEX "SYSTEM"."IDX_TEAM.NAME_WS" ON "SYSTEM"."TEAM" ("NAME", "WS_KEY") TABLESPACE "SYSTEM" ;
/  
--------------------------------------------------------
--  DDL for Table ROTATION
--------------------------------------------------------
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE "SYSTEM"."ROTATION"';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/
CREATE TABLE "SYSTEM"."ROTATION" 
   (	
    "ROTATION_KEY" NUMBER(19,0) GENERATED ALWAYS AS IDENTITY, 
	"NAME" NVARCHAR2(64) NULL, 
	"DESCRIPTION" NVARCHAR2(128) NULL,
	"WS_KEY" NUMBER(19,0) NULL, 
	PRIMARY KEY (ROTATION_KEY)
   ) TABLESPACE "SYSTEM" ;
/
--------------------------------------------------------
--  DDL for Table ROTATION_SEGMENT
--------------------------------------------------------
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE "SYSTEM"."ROTATION_SEGMENT"';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/
CREATE TABLE "SYSTEM"."ROTATION_SEGMENT" 
   (	
    "SEGMENT_KEY" NUMBER(19,0) GENERATED ALWAYS AS IDENTITY,  
	"ROTATION_KEY" NUMBER(19,0) NULL, 
	"SEQUENCE" NUMBER(5,0) NULL, 
	"SHIFT_KEY" NUMBER(19,0) NULL, 
	"DAYS_ON" NUMBER(5,0) NULL, 
	"DAYS_OFF" NUMBER(5,0) NULL,
	PRIMARY KEY (SEGMENT_KEY)
   ) TABLESPACE "SYSTEM" ;
/
--------------------------------------------------------
--  DDL for Table NON_WORKING_PERIOD
--------------------------------------------------------
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE "SYSTEM"."NON_WORKING_PERIOD"';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/
CREATE TABLE "SYSTEM"."NON_WORKING_PERIOD" 
   (	
    "PERIOD_KEY" NUMBER(19,0) GENERATED ALWAYS AS IDENTITY,   
	"NAME" NVARCHAR2(64) NULL, 
	"DESCRIPTION" NVARCHAR2(128) NULL, 
	"START_DATE_TIME" TIMESTAMP(3) NULL, 
	"DURATION" NUMBER(19,0) NULL, 
	"WS_KEY" NUMBER(19,0) NULL, 
	"LOSS" NVARCHAR2(32) NULL,
	PRIMARY KEY (PERIOD_KEY)
   ) TABLESPACE "SYSTEM" ;
/
--------------------------------------------------------
--  DDL for Table BREAK_PERIOD
--------------------------------------------------------
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE "SYSTEM"."BREAK_PERIOD"';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/
CREATE TABLE "SYSTEM"."BREAK_PERIOD" 
   (	
    "BREAK_KEY" NUMBER(19,0) GENERATED ALWAYS AS IDENTITY,   
	"NAME" NVARCHAR2(64) NULL, 
	"DESCRIPTION" NVARCHAR2(128) NULL, 
	"START_TIME" TIMESTAMP(3) NULL, 
	"DURATION" NUMBER(19,0) NULL, 
	"SHIFT_KEY" NUMBER(19,0) NULL, 
	"LOSS" NVARCHAR2(32) NULL,
	PRIMARY KEY (BREAK_KEY)
   ) TABLESPACE "SYSTEM" ;
/
--------------------------------------------------------
--  DDL for Table COLLECTOR
--------------------------------------------------------
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE "SYSTEM"."COLLECTOR"';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/
CREATE TABLE "SYSTEM"."COLLECTOR" 
   (	
    "COLLECT_KEY" NUMBER(19,0) GENERATED ALWAYS AS IDENTITY,
	"VERSION" NUMBER(10,0) NULL, 
	"NAME" NVARCHAR2(64) NULL, 
	"DESCRIPTION" NVARCHAR2(128) NULL, 
	"STATE" NVARCHAR2(16) NULL, 
	"HOST" NVARCHAR2(64) NULL, 
	"BROKER_HOST" NVARCHAR2(64) NULL, 
	"BROKER_PORT" NUMBER(10,0) NULL,
	"BROKER_USER" NVARCHAR2(64) NULL,
	"BROKER_PWD" NVARCHAR2(64) NULL,
	"BROKER_TYPE" NVARCHAR2(32) NULL,
	"SOURCE_KEY" NUMBER(19,0) NULL,
	PRIMARY KEY (COLLECT_KEY)
   ) TABLESPACE "SYSTEM" ;
/   
CREATE UNIQUE INDEX "SYSTEM"."IDX_COLLECT.NAME" ON "SYSTEM"."COLLECTOR" ("NAME") TABLESPACE "SYSTEM" ;
/ 
--------------------------------------------------------
--  DDL for Table OEE_EVENT
--------------------------------------------------------
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE "SYSTEM"."OEE_EVENT"';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/
CREATE TABLE "SYSTEM"."OEE_EVENT" 
   (	
    "EVENT_KEY" NUMBER(19,0) GENERATED ALWAYS AS IDENTITY, 
	"ENT_KEY" NUMBER(19,0) NOT NULL, 
	"START_TIME" TIMESTAMP(3) NOT NULL, 
	"START_TIME_OFFSET" NUMBER(10,0) NOT NULL,
	"END_TIME" TIMESTAMP(3) NULL, 
	"END_TIME_OFFSET" NUMBER(10,0) NULL,
	"SHIFT_KEY" NUMBER(19,0) NULL, 
	"TEAM_KEY" NUMBER(19,0) NULL, 
	"REASON_KEY" NUMBER(19,0) NULL, 
	"DURATION" NUMBER(19,0) NULL, 
	"EVENT_TYPE" NVARCHAR2(16) NOT NULL, 
	"AMOUNT" BINARY_DOUBLE NULL, 
	"UOM_KEY" NUMBER(19,0) NULL, 
	"MATL_KEY" NUMBER(19,0) NULL, 
	"JOB" NVARCHAR2(64) NULL,
	"IN_VALUE" NVARCHAR2(64) NULL,
	"SOURCE_ID" NVARCHAR2(64) NULL,
	"COLLECTOR" NVARCHAR2(64) NULL,
	PRIMARY KEY (EVENT_KEY)
   ) TABLESPACE "SYSTEM" ;
/
CREATE UNIQUE INDEX "SYSTEM"."IDX_ENT_TYPE_START" ON "SYSTEM"."OEE_EVENT" ("ENT_KEY", "EVENT_TYPE", "START_TIME") TABLESPACE "SYSTEM" ;
/ 
--------------------------------------------------------
--  DDL for Table ENTITY_SCHEDULE
--------------------------------------------------------
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE "SYSTEM"."ENTITY_SCHEDULE"';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/
CREATE TABLE "SYSTEM"."ENTITY_SCHEDULE" 
   (	
    "ES_KEY" NUMBER(19,0) GENERATED ALWAYS AS IDENTITY,  
	"ENT_KEY" NUMBER(19,0) NULL, 
	"WS_KEY" NUMBER(19,0) NULL, 
	"START_DATE_TIME" TIMESTAMP(3) NOT NULL, 
	"END_DATE_TIME" TIMESTAMP(3) NOT NULL, 
	PRIMARY KEY (ES_KEY)
   ) TABLESPACE "SYSTEM" ;
/ 


   

