-- HSQLDB schema migration script file, schema version 4 to 5
-- set to your schema
SET AUTOCOMMIT TRUE;

/****** BREAK table ******/
DROP TABLE BREAK IF EXISTS;

CREATE CACHED TABLE BREAK (
	BREAK_KEY bigint GENERATED BY DEFAULT AS IDENTITY,
	NAME nvarchar(64) NULL,
	DESCRIPTION nvarchar(128) NULL,
	START_TIME time(3) NULL,
	DURATION bigint NULL,
	SHIFT_KEY bigint NULL,
	LOSS nvarchar(32) NULL,
	PRIMARY KEY (BREAK_KEY)
);